server.port=${BIRTHDAY_BOT_PORT:8080}

telegram.bot.token=${BIRTHDAY_BOT_TOKEN:tabriknoma_birthday_bot}
telegram.bot.username=${BIRTHDAY_BOT_USERNAME:7771741080:AAF8B2ObKX0-1I5xirKMLEezFwwDhx1kNX4}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/chaqmoq_platform}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root123}
spring.jpa.hibernate.ddl-auto=update
